# Generated by Django 4.0.1 on 2022-03-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOM_vis_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coord',
            old_name='GeoDome',
            new_name='geoDome',
        ),
        migrations.AddField(
            model_name='coord',
            name='coOrd',
            field=models.IntegerField(default=0),
        ),
    ]
