# Generated by Django 4.0.1 on 2022-03-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOM_vis_app', '0002_rename_geodome_coord_geodome_coord_coord'),
    ]

    operations = [
        migrations.AddField(
            model_name='coord',
            name='triangle',
            field=models.FloatField(default=0),
        ),
    ]
