# Generated by Django 4.0.1 on 2022-03-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOM_vis_app', '0003_coord_triangle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoOrd',
            new_name='CoOrdDome',
        ),
    ]
