# Generated by Django 4.0.1 on 2022-03-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOM_vis_app', '0004_rename_coord_coorddome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coorddome',
            old_name='triangle',
            new_name='value',
        ),
        migrations.AddField(
            model_name='coorddome',
            name='xyz',
            field=models.IntegerField(default=0),
        ),
    ]
