# Generated by Django 4.0.1 on 2022-03-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOM_vis_app', '0005_rename_triangle_coorddome_value_coorddome_xyz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coorddome',
            old_name='coOrd',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='coorddome',
            old_name='xyz',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='coorddome',
            name='value',
        ),
        migrations.AddField(
            model_name='coorddome',
            name='z',
            field=models.IntegerField(default=0),
        ),
    ]
