# Generated by Django 4.0.1 on 2022-03-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOM_vis_app', '0006_rename_coord_coorddome_x_rename_xyz_coorddome_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coorddome',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coorddome',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coorddome',
            name='z',
            field=models.FloatField(default=0),
        ),
    ]
