# Generated by Django 4.0.1 on 2022-03-16 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOM_vis_app', '0007_alter_coorddome_x_alter_coorddome_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOrd2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('geoDome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SOM_vis_app.geodome')),
            ],
        ),
    ]
