# Generated by Django 4.0.1 on 2022-05-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOM_vis_app', '0009_coord2d_colour_coorddome_colour_triangle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triangle',
            name='toDraw',
        ),
    ]
